### ISSUE TITLE
Question: Can I use this tool for commercial purpose? 

### ISSUE THREAD

**Issue by Pasupathi-Rajamanickam** [canonical/documentation-builder#129]
I was searching for a good documentation platform and this one is so calm and perfect for my need. But my product is commercial. Can I use html generated by this tool for commercial purpose?

**Comment by nottrobin** [comment]
Hi @Pasupathi-Rajamanickam. You're welcome to use documentation-builder to build documentation as you like, including for commercial purposes.

What you can't do is create a derivative piece of software from documentation-builder and charge money for it (as it's a GPL license). But that shouldn't prevent the usage you're talking about.

**Comment by Pasupathi-Rajamanickam** [comment]
Thank you. I'm signing off this tool for my product documentation. 😀
